layout_spectrum: 0.9361702
typography_spectrum: 0.04255319
color:
  saturation: 0.2617021
  lightness: 0.1723404
  brandStrength: 0.01598106
  brandColors:
    - '#FFFFFF'
    - '#050505'
    - '#56512B'
    - '#D2AE70'
    - '#8C7A62'
  rhythmicContrast: 0.337947
name: Mountain Folk Mushrooms
